/* eslint-disable */
/* This is an autogenerated file. Do not edit this file directly! */
export type DemoGetFilms = {
  allFilms: {
    totalCount: number | null
    films:
      | ({
          id: string
          title: string | null
          created: string | null
        } | null)[]
      | null
  } | null
}
export type DemoGetFilmsVariables = {}
